name: dbfold
channels:
  - conda-forge
dependencies:
  - python==3.10
  - numpy
  - pandas
  - pymbar
  - matplotlib
  - seaborn
  - natsort
  - hmmlearn
  - pyyaml
  - ipykernel
  - nb_conda_kernels
  - mdtraj
